version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    volumes:
      - ./data/base:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - "3306:3306"
  app:
    depends_on:
      - mysqldb
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"

